package.json, src/bento/trialDetailData.js, src/pages/trialDetail/trialDetailView.js, src/pages/trialDetail/views/BiospecimenProfile.js, src/pages/trialDetail/views/overview/overview.js, src/pages/trialDetail/views/overview/overviewThemeConfig.js
Add Biospecimen Profile under Trial Detail page
=> CTDC-913 (Biospecimen Profile)

src/pages/trialDetail/studyDetailsStyle.js, src/pages/trialDetail/views/BiospecimenProfile.js, src/pages/trialDetail/views/overview/overview.js
Trial Detail - Image Collection Section
=> CTDC-912 (Image Collection)

src/bento/dashTemplate.js, src/bento/dashboardTabData.js, src/components/Layout/LayoutView.js, src/pages/dashTemplate/DashTemplateController.js, src/utils/colors.js
In this PR, all of the widget under Explore page has been implemented using Mock API.
Related Tickets:
- CTDC-1054 ["Diagnosis and Stage","Sex and Gender","Race and Ethnicity"]
- CTDC-1055 ["Therapy"]
- CTDC-1056 ["Biospecimens and Timepoints"]
- CTDC-1057 ["Files"]
=> Explore Widgets

src/bento/dashboardTabData.js, src/bento/globalStatsData.js, src/components/Stats/StatsState.js, src/pages/trialDetail/trialDetailView.js
Implemented Global Stats bar using Mock API
=> Global Stats bar

src/config/globalHeaderData.js
Related ticket  [CTDC-903](https://tracker.nci.nih.gov/browse/CTDC-903)
=> Update the menu list order to match US

src/components/Footer/FooterDesktop.js, src/config/globalFooterData.js
Related Ticket: [CTDC-904](https://tracker.nci.nih.gov/browse/CTDC-904)
=> Update Contact Email under Footer

src/bento/dashboardTabData.js, src/pages/dashTemplate/tabs/DefaultTabTheme.js, src/pages/dashTemplate/tabs/wrapperConfig/Theme.js, src/pages/dashTemplate/tabs/wrapperConfig/Wrapper.js, src/utils/graphqlClient.js
Related Ticket: [CTDC-1060](https://tracker.nci.nih.gov/browse/CTDC-1060)
=> Biospecimen Grid Table

src/bento/dashboardTabData.js, src/pages/dashTemplate/tabs/DefaultTabTheme.js, src/pages/dashTemplate/tabs/wrapperConfig/Theme.js, src/pages/dashTemplate/tabs/wrapperConfig/Wrapper.js, src/utils/graphqlClient.js
Explore Participants Table using Mock API
=> Explore Participants Table

src/bento/dashboardTabData.js, src/pages/dashTemplate/tabs/DefaultTabTheme.js, src/pages/dashTemplate/tabs/wrapperConfig/Theme.js
Related Ticket: [CTDC-1061](https://tracker.nci.nih.gov/browse/CTDC-1061)
=> Files Table Under Explore using Mock API

src/bento/landingPageData.js, src/components/InteractiveHero/InteractiveHero.js, src/pages/landing/landingController.js
Added backend support to homepage
=> Added backend support to homepage

src/bento/dashboardTabData.js
Based on the updates made to the GraphQL API, as indicated in [this pull request](https://github.com/CBIIT/crdc-ctdc-backend/pull/7), the APIs for Tables on the Explore page have been refreshed.
=> CTDC-1100 (Explore Tables)

src/components/Layout/LayoutView.js, src/content/prod/aboutPagesContent.yaml
Ticket: 
[CTDC-1102](https://tracker.nci.nih.gov/browse/CTDC-1102) 
[CTDC-1175](https://tracker.nci.nih.gov/browse/CTDC-1175)
=> update the static page and routers

src/pages/cart/cartView.style.js, src/pages/cart/tableConfig/CustomHeaderRemover.js, src/pages/cart/tableConfig/Theme.js, src/pages/cart/tooltip/customToolTipContent.js, src/pages/cart/tooltip/customToolTipContent.style.js, src/pages/cart/wrapperConfig/Theme.js, src/pages/fileCentricCart/cartView.style.js
* tooltip customization on downlaod manifest and remove buttons
=> * Gap between the nav bar and the table in file cart reduced

src/bento/dashboardTabData.js
=> Fix Biospecimens tab count

src/components/Footer/FooterDesktop.js, src/components/Footer/FooterMobile.js, src/components/Footer/FooterTablet.js, src/components/Header/components/SearchBarDesktop.js, src/components/Header/components/SearchBarMobile.js, src/components/Header/components/SearchBarTablet.js
[CTDC-1210](https://tracker.nci.nih.gov/browse/CTDC-1210) 
Fixed the 508 errors, leave the contrast  Error as is. defer to Hannah's design QA
=> CTDC-1210 Fix 508 errors

src/bento/dashboardTabData.js
Based on [this BE PR](https://github.com/CBIIT/crdc-ctdc-backend/pull/11), CTDC frontend code is also updated to change query property from "snomed_disease_code" to "stage_of_disease" under Explore Tables(`Participants`, `Biospecimens`, `Files`)
=> Change Query Property from "snomed_disease_code" to "stage_of_disease"

src/bento/dashTemplate.js, src/bento/dashboardTabData.js, src/bento/fileCentricCartWorkflowData.js, src/bento/globalStatsData.js
Update GraphQL properties to align with new schema:
- Rename `ctep_disease_code` to `snomed_disease_term`
- Rename `participantCountByCtepDiseaseCode` to `participantCountBySnomedDiseaseTerm`
- Rename `filterParticipantCountByCtepDiseaseCode` to `filterParticipantCountBySnomedDiseaseTerm`"
Related BE PR: https://github.com/CBIIT/crdc-ctdc-backend/pull/15
=> Update GraphQL properties to align with new schema

src/bento/dashboardTabData.js, src/pages/dashTemplate/tabs/wrapperConfig/Wrapper.js
- Update (Participants, Biospecimen, Files) Query for adding Selected File to reflect BE API changes
- Add `applyActiveFilter` flag for "Add Selected Files" Button 
Related BE PR: https://github.com/CBIIT/crdc-ctdc-backend/pull/17
Helpful Documents:
- https://github.com/CBIIT/bento-frontend/blob/ICDC_table_features/packages/paginated-table/Add_Selected_Files_Orange_button_README.md
- https://github.com/CBIIT/bento-frontend/blob/ICDC_table_features/packages/paginated-table/Add_ALL_Files__BLUE_ButtonREADME.md
=> Bug fixes 

public/index.html, src/components/Header/HeaderDesktop.js, src/components/Header/components/LogoDesktop.js, src/components/Header/components/NavbarDesktop.js
- Fixed Header style to match Figma comment
- Added more fonts weight
=> CTDC-1204: Fix Header Style

src/bento/dashboardTabData.js
- Update CSV file names for all downloadable tables under Participants, Biospecimens, and Data Files tabs
=> CTDC-1295: CSV File Name

src/pages/cart/tableConfig/Theme.js
- Update the style of the button under the confirmation dialog that appears when users attempt to remove all files from the cart table header.
=> CTDC-1257: Update Button style

src/pages/dashTemplate/widget/SunburstStyle.js, src/pages/dashTemplate/widget/WidgetView.js
- Fix sunburst wiggling issue by applying a custom style to the sunburst widget, setting a width of 250px for the title underneath the sunburst.
=> CTDC-1247: Fix sunburst wiggling issue

src/bento/dashTemplate.js
- Replace '#C2E5DC' with '#0A8B8B' for Improved Visual Consistency
=> CTDC-1248: Fix Highlight issue

src/bento/dashTemplate.js
hide the search function on facet search cate Filter by Participants
=> hide the search function on facet search cate Filter by Participants

src/bento/fileCentricCartWorkflowData.js
hide the checkbox on cart page
=> hide the checkbox on cart page

src/components/ScrollButton/ScrollButtonView.js
=> Revert "Add a scrollbar exception for the Explorer page."

src/bento/dashTemplate.js, src/pages/dashTemplate/sideBar/BentoFacetFilterStyle.js
- Fixed text overlap issue under facet section
- Add arrow drop down icon to Participant Facet section
=> CTDC-1317: Dashboard fixes

src/components/InteractiveHero/InteractiveHero.js
Removed counts from the inactive settings on the hero image
=> Removed counts from the inactive settings on the hero image.

src/components/Auth/components/nihLoginSuccess.js, src/pages/cart/tableConfig/CustomHeaderRemover.js
Fix bug : Change button text to 'Clear Cart' in cart grid
Fix bug: Login->eRA Commons-> Cancel->Login page link redirects to 404 Error.
=> Fix bug ticket  CTDC-1351 and CTDC-1324

src/components/ActivitiesController/index.js, src/components/Layout/LayoutView.js
Add feature to extend session on every page load. @Nahomtes   See how to check user is sign in or not.
=> add session extension

src/bento/globalStatsData.js, src/bento/studyDetailData.js, src/components/Stats/StatsBarView.js, src/pages/studyDetail/studyDetailsStyle.js, src/pages/studyDetail/studyDetailsThemeConfig.js, src/pages/studyDetail/views/BiospecimenProfile.js, src/pages/studyDetail/views/overview/overview.js, src/pages/studyDetail/views/overview/overviewThemeConfig.js
=> CTDC-1345: Design QA for Study page 

src/config/globalFooterData.js, src/config/globalHeaderData.js
Remove Home from navigation ribbon 
Update “policies” links (order and labels) to align with Cancer.gov footer
=> CTDC-1358 & CTDC-1359

src/pages/search/Cards/AboutCard.js, src/pages/search/Cards/PropertyItem.js, src/pages/search/Cards/ValueCard.js, src/pages/search/Cards/biospecimen/style.js, src/pages/search/Cards/participant/style.js, src/pages/search/styles.js
=> CTDC-1326: Global Search - Design QA 

src/bento/dashboardTabData.js, src/pages/dashTemplate/widget/WidgetView.js
- Update the maximum file size to be downloadable under File Tab for Dashboard page to be 10 MB or 80,000,000 bits
- Hide switch to change to toggle between dark or light theme
Related Ticket: CTDC-1147
=> Fixes on Dashboard

src/bento/dashboardTabData.js, src/pages/dashTemplate/tabs/tableConfig/Column.js
- Add custom element to remove square brackets from given cell string
=> Remove square brackets

src/pages/studyDetail/views/BiospecimenProfile.js
Changed samples to Biospecimens on the study detail page
=> Changed samples to Biospecimens on the study detail page

src/bento/studyDetailData.js, src/components/Footer/FooterDesktop.js, src/components/GraphqlClient/GraphqlView.js, src/components/Header/HeaderDesktop.js, src/components/Header/USABanner.js, src/components/Header/components/NavbarDesktop.js, src/pages/dashTemplate/DashTemplateStyle.js, src/pages/studyDetail/studyDetailsStyle.js, src/pages/studyDetail/views/BiospecimenProfile.js, src/pages/studyDetail/views/overview/overview.js, src/pages/studyDetail/views/overview/overviewThemeConfig.js, src/themes/light.js
Fix Studies page to be more responsive and fix feedback from Design QA
Add max width of 1800px through out CTDC pages
Switch the tab order of `TYPE` and `TIMEPOINT` under Studies page
=> CTDC-1345: Responsiveness under Studies page 

src/bento/globalStatsData.js, src/components/Header/HeaderMobile.js, src/components/Header/HeaderTablet.js, src/components/Stats/StatsBarView.js, src/pages/search/Cards/participant/ParticipantCard.js, src/pages/search/Cards/participant/style.js, src/pages/studyDetail/studyDetailsStyle.js, src/pages/studyDetail/views/overview/overview.js
GitHub PR Description:
In this PR, the following changes have been made:
- Fixed the issue where content under the Study page was inaccessible by keyboard navigation.
- Updated `THERAPIES` to `TARGETED THERAPIES` within the Global Stats Bar.
- Refactored the style of the Global Stats Bar to enhance responsiveness.
- Added `stage_of_disease` under the Search > Participants Card.
Related Tickets: CTDC-1417, CTDC-1428, CTDC-1435
=> CTDC-1417, CTDC-1428, CTDC-1435

src/bento/dashboardTabData.js, src/pages/dashTemplate/tabs/tableConfig/Column.js
Added sub text under gender table column name
=> Added sub text under gender table column name

src/bento/globalStatsData.js, src/components/GraphqlClient/GraphqlView.js
- Improved GraphQL Page for 508 compliance with color contrast
- Centered Stats Bar Item Vertically
=> CTDC-1436: 508 Compliance under GraphQL Page

src/bento/dashboardTabData.js, src/bento/search.js, src/pages/dashTemplate/tabs/tableConfig/Column.js
Added changes to File name and Gs file name
Related BE PR: https://github.com/CBIIT/crdc-ctdc-backend/pull/42
=> Added changes to File name and Gs file name

src/bento/dashTemplate.js, src/bento/dashboardTabData.js, src/bento/fileCentricCartWorkflowData.js, src/bento/studyDetailData.js, src/pages/dashTemplate/tabs/tableConfig/Column.js, src/pages/search/Cards/biospecimen/BiospecimenCard.js
=> Update specimen properties

src/pages/studyDetail/views/BiospecimenProfile.js, src/pages/studyDetail/views/overview/components/ZipDownloadView.js, src/pages/studyDetail/views/overview/overview.js
Apply Design QA feedback under Studies page
=> Apply Design QA feedback under Studies page

src/pages/about/requestAccess.js
Added a sub list for the line in question
https://tracker.nci.nih.gov/browse/CTDC-1450
=> Added a sub list for the line in question

src/content/prod/aboutPagesContent.yaml
Link update :https://tracker.nci.nih.gov/browse/CTDC-1201
Original ticket: https://tracker.nci.nih.gov/browse/CTDC-1465
=> Fixing links and adding a "the" back in

src/bento/studyDetailData.js, src/pages/studyDetail/studyDetailController.js, src/pages/studyDetail/studyDetailView.js, src/pages/studyDetail/views/overview/overview.js
- Hide `Additional Details `tab
- Change `STUDY DESCRIPTION` to `Study Name`
- Refactor
=> CTDC-1497: Update Studies page

src/bento/aboutPagesRoutes.js, src/config/globalHeaderData.js, src/content/prod/aboutPagesContent.yaml, src/pages/about/requestAccess.js
Plain text update on Request Access and For Developer
=> CTDC-1471: Plain text update on Request Access and For Developer

src/bento/dashboardTabData.js, src/bento/fileCentricCartWorkflowData.js
Bug fix for biospecimen tab selected files not adding to cart
https://tracker.nci.nih.gov/browse/CTDC-1503
=> Bug fix for biospecimen tab selected files not adding to cart

src/content/prod/aboutPagesContent.yaml
https://tracker.nci.nih.gov/browse/CTDC-1470
https://tracker.nci.nih.gov/browse/CTDC-1469
https://tracker.nci.nih.gov/browse/CTDC-1468
=> Text changes

src/bento/siteWideConfig.js, src/components/Auth/components/nihLoginSuccess.js, src/components/Layout/LayoutView.js, src/store/index.js, src/store/utils.js, src/utils/useVisitedPageSync.js
This PR introduces functionality to persist the Redux state and improve login redirection behavior by storing relevant data in local storage.
- **Redux State Persistence**: Utilizes the key `ctdcReduxState` to store the Redux state data in local storage. Upon initialization, the application loads the stored state, ensuring that user interactions are preserved across sessions.
- **Login Redirection Improvement**: Introduces the key `lastVisitedHash` to track the last saved page. This enables seamless redirection to the correct page after user authentication.
=> State Persistence & Login Redirect Enhancement

src/components/DocumentDownload/DocumentDownloadView.js, src/pages/studyDetail/views/overview/components/ZipDownloadView.js
Update the functionality to fetch and download files
=> Update the functionality to fetch and download files

src/components/GraphqlClient/GraphqlView.js
https://tracker.nci.nih.gov/browse/CTDC-1474
=> Updates to text for graphql

src/bento/dashTemplate.js, src/bento/dashboardTabData.js, src/bento/fileCentricCartWorkflowData.js, src/bento/studyDetailData.js, src/pages/dashTemplate/tabs/tableConfig/Column.js, src/pages/search/Cards/biospecimen/BiospecimenCard.js
Update treatment of analyte property
https://tracker.nci.nih.gov/browse/CTDC-1509
=> Update treatment of analyte property

src/bento/dashboardTabData.js, src/bento/fileCentricCartWorkflowData.js, src/bento/globalStatsData.js, src/bento/search.js, src/pages/search/Cards/biospecimen/BiospecimenCard.js
Remove un-need property of `specimen_type`
=> CTDC-1509-fix: Remove leftover specimen_type property

src/components/About/aboutBodyView.js, src/components/GraphqlClient/GraphqlView.js, src/content/prod/aboutPagesContent.yaml
https://tracker.nci.nih.gov/browse/CTDC-1506
https://tracker.nci.nih.gov/browse/CTDC-1511
=> Ctdc 1506 and 1511

src/components/GraphqlClient/GraphqlView.js, src/content/prod/aboutPagesContent.yaml
=> update the plain language

src/bento/dashboardTabData.js, src/components/DocumentDownload/DocumentDownloadView.js, src/components/Notifications/NotifactionView.js, src/components/Notifications/NotificationFunctions.js, src/pages/about/requestAccess.js, src/pages/studyDetail/views/overview/components/ZipDownloadView.js, src/pages/studyDetail/views/overview/overview.js
- This PR will show an authenticated user who is not authorized to see a message indicating why their file download from the Explore Files grid or Studies page cannot proceed.
- Added functionality to update the style of the Notification component
=> CTDC-1516: Handling File Download for not authorized user

src/pages/search/Cards/AboutCard.js
In this PR, the Global Search ellipses functionality has been modified to remove all punctuation at the end of sentences and add ellipses, including after the last match on the page.
Related Ticket: CTDC-1515
=> Global Search ellipses

src/pages/landing/landingView.js
LandingView.js had a const named LandingController which is confusing since there is another file already called LandingController.js
Changed variable name to match file name
=> Changed naming for clarity

src/config/globalFooterData.js
Update Update FE version from `1.0.0` to `1.0.1`
=> Update FE version to 1.0.1

src/config/globalFooterData.js
Propagates changes from 1.0.1 to 1.1.0
=> Merge 1.0.1 into 1.1.0

package.json, src/pages/dashTemplate/filterQueryBar/QueryBarView.js, src/pages/dashTemplate/sideBar/BentoFacetFilterStyle.js, src/pages/dashTemplate/sideBar/FilterThemeConfig.js, src/pages/dashTemplate/tabs/DefaultTabTheme.js
[CTDC-1534](https://tracker.nci.nih.gov/browse/CTDC-1534) Fix 508 Compliance issues under Explore page
Refer to Figma comment `#2-3, 12-18`
comment `#2-3`: (No changes)
comment `#16-#18`: (No changes)
(Ignore the link under each commit message)
=> CTDC-1534: Fix 508 Compliance issues

src/bento/dashTemplate.js, src/bento/dashboardTabData.js
https://tracker.nci.nih.gov/browse/CTDC-1354 details updates required
changes to Race and ethnicities sunbrust to be a donut just displaying race
changes to diagnosis and stage of disease sunbrust to be a donut just displaying diagnosis
=> Change starbursts to donuts respectivly

public/injectEnv.js, src/components/Cart/CartView.js, src/components/Header/components/NavbarDesktop.js, src/config/globalHeaderData.js
- Added spacing and pipe character between Login and Cart links in main level of navigation. 
- Added home button on the far left of the menu
- Renamed "For Developers" to "Resources"
- Reorganized nav menu items under "Resources" to be "GraphQL, Additional Information, GitHub"
=> CTDC-1424: Modify the main navigation bar

public/injectEnv.js, src/bento/search.js, src/pages/search/Cards/participant/ParticipantCard.js, src/pages/search/searchView.js
Removed the Gender(reported_gender) property from Search page
[CTDC-1618](https://tracker.nci.nih.gov/browse/CTDC-1618)
=> CTDC-618: Remove "Gender" Property from Search page

src/components/Footer/FooterDesktop.js, src/components/Footer/FooterMobile.js, src/components/Footer/FooterTablet.js, src/config/globalFooterData.js
Updated FE and BE versions in preparation for the upcoming release.
=> CTDC-1626: Update FE and BE Version

src/components/BarChartV2/bar-chart-v2.js
Updated the legend in modal so that when hovering over an item with a white background, the legend includes a drop shadow on the bottom edge of hovered item.
=> CTDC-1625: Modal Legend Update

src/components/BarChartV2/bar-chart-v2.js
changed max y axis value to increment to the next 100
=> CTDC-1639: biospecimen page scaling inconsistencies

src/pages/studyDetail/views/BiospecimenProfile.js, src/pages/studyDetail/views/biospecimen-profile-modal-store.js, src/pages/studyDetail/views/biospecimen-profile-modal.js
- changed biospecimen profile modal to take in value of current tab from biospecimen profile
- sets current tab in biospecimen profile modal based on value imported
=> CTDC-1641: "Expanded View" opens with a different tab

public/injectEnv.js, src/bento/aboutPagesRoutes.js, src/components/Layout/LayoutView.js, src/pages/dmn/index.js
Add Data Model Navigator,  The environment variable yet need to updated.
=> Add Data Model Navigator

src/components/PaginatedTable/Customize/DataAvailability/ColGrouping.js, src/components/PaginatedTable/Customize/DataAvailability/TableCell.js
- Ensured that any null values in the `image_collection` property on the Studies page are properly handled by filtering them out.
- Updated the tooltip text to align with how ICDC displays CRDC Links.
- Adjusted the tooltip background color for consistency.
- Refactor code
=> CTDC-1548: Handle Null Values & Tooltip Updates

public/style/graphql.css, src/components/GraphqlClient/GraphqlView.js, src/pages/about/aboutHeader.js
Changed query variables color, changed styles associated with data color
Address "Document should have one main landmark" and color contrast issue
=> CTDC-1446: 508 Compliance Issues on GraphQL Page: Form Label and Keyboard Access issues

src/bento/fileCentricCartWorkflowData.js, src/pages/fileCentricCart/components/dropdown/DropDownView.js, src/pages/fileCentricCart/utils.js
- Fixed how User comment is added to the first row after the header while keeping the rest of row empty
- Added validation for the header and keysToInclude
=> CTDC-1690: Resolve Issue with Export to CGC

src/bento/studiesData.js, src/components/DataAvailabilityTable/StudiesTable.js, src/components/DataAvailabilityTable/tableThemeConfig.js, src/components/PaginatedTable/Customize/CellView.js, src/components/PaginatedTable/Customize/DataAvailability/TableCell.js, src/components/PaginatedTable/Customize/ExtendedView.js, src/components/PaginatedTable/Customize/Types.js, src/components/PaginatedTable/utils.js, src/pages/studies/studiesController.js, src/pages/studies/studiesView.js
CTDC-1699: Update Studies page to use the new endpoints to improve load time
CTDC-1701: fix issue related to the Additional CRDC Nodes column under study Details page -> Download table as csv
~To test this PR, User have to load the interop_data index into local opensearch and use localhost graphql api~
=> CTDC-1699 & CTDC-1701: Improve load time and format download data

public/injectEnv.js, src/pages/dmn/index.js
- add allow download
- Update local `REACT_APP_DMN_URL` value to point to dev configuration
=> add allow download

src/pages/landing/landingView.js
- Fixed URL to the studies page
=> Fix Studies page URL

src/pages/fileCentricCart/components/dropdown/DropDownView.js
Refactor Cart tooltip titles to always render content
=> Refactor Cart tooltip titles to always render content
